### PR TITLE
Kissat bindings

### PR DESCRIPTION
**Pull request by lixitrixi**
Here I the kissat-rs module as cargo dependencies. This will hopefully help with modularity and size, and if we need to add to the libraries this can be changed to use our fork.

Next up is working on CI and unit testing for our SAT solver bindings. I'll try to find a public source of test DIMACS files and set up automatically running them through the bindings.

### CODE REVIEW

**Comment by lixitrixi** [comment]
Also in this PR I've added build files generated by Minion and anything else to .gitignore, since it was an issue for me.

**Comment by ozgurakgun** [comment]
by merging #6 I created a (trivial) merge conflict here, sorry! can you fix it please @lixitrixi?

**Comment by lixitrixi** [comment]
I've added a general import rule to Cargo.toml which imports all `solvers/*`. Let me know if that works! The empty exclude is just to remind of the syntax in case people need to temporarily exclude a solver.

**Comment by lixitrixi** [comment]
This should now be good to merge @ozgurakgun !

**Comment by niklasdewally** [comment]
> I've added a general import rule to Cargo.toml which imports all `solvers/*`. Let me know if that works! The empty exclude is just to remind of the syntax in case people need to temporarily exclude a solver.

if running cargo build in the root directory tries to build minion, it should be working.

**Comment by ozgurakgun** [comment]
not a big deal but I slightly prefer explicitly listing the solvers.

**Comment by lixitrixi** [comment]
I've pulled and made the change back to explicitly listing them, but I get this error when building:

```
error: failed to run custom build command for `chuffed_rs v0.1.0 (/Users/felixleitner/dev/repos/conjure-oxide/solvers/chuffed)`

Caused by:
  process didn't exit successfully: `/Users/felixleitner/dev/repos/conjure-oxide/target/debug/build/chuffed_rs-0412293b45d76914/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-rerun-if-changed=vendor
  cargo:rerun-if-changed=build.rs
  cargo:rustc-link-search=all=./solvers/chuffed/vendor/build/
  cargo:rustc-link-lib=static=chuffed
  cargo:rustc-link-lib=static=chuffed_fzn
  cargo:rustc-link-lib=dylib=c++
  stdout
  ------ BUILDING ------

  stderr
  build.sh: line 11: cmake: command not found
  build.sh: line 12: cmake: command not found


  --- stderr
  thread 'main' panicked at 'build.sh has non zero exit status', solvers/chuffed/build.rs:49:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by niklasdewally** [comment]
> I've pulled and made the change back to explicitly listing them, but I get this error when building:
> 
> ```
> error: failed to run custom build command for `chuffed_rs v0.1.0 (/Users/felixleitner/dev/repos/conjure-oxide/solvers/chuffed)`
> 
> Caused by:
>   process didn't exit successfully: `/Users/felixleitner/dev/repos/conjure-oxide/target/debug/build/chuffed_rs-0412293b45d76914/build-script-build` (exit status: 101)
>   --- stdout
>   cargo:rustc-rerun-if-changed=vendor
>   cargo:rerun-if-changed=build.rs
>   cargo:rustc-link-search=all=./solvers/chuffed/vendor/build/
>   cargo:rustc-link-lib=static=chuffed
>   cargo:rustc-link-lib=static=chuffed_fzn
>   cargo:rustc-link-lib=dylib=c++
>   stdout
>   ------ BUILDING ------
> 
>   stderr
>   build.sh: line 11: cmake: command not found
>   build.sh: line 12: cmake: command not found
> 
> 
>   --- stderr
>   thread 'main' panicked at 'build.sh has non zero exit status', solvers/chuffed/build.rs:49:9
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```
> ```

```
brew install cmake
```

**Comment by lixitrixi** [comment]
Nooooo I was about to change it back to listing them

**Comment by ozgurakgun** [comment]
Ooops, I thought you had already done that :) another PR?

**Comment by lixitrixi** [comment]
> Ooops, I thought you had already done that :) another PR?

#12 @ozgurakgun

**Pull request merged**
