### PR TITLE
Issues with creating XYZ problem in cpp

### PR DESCRIPTION
**Pull request by Kieranoski702**
I'm currently using this PR as a platform to get support rather than to contribute something immediately.

I have been having issues with getting a version of the XYZ problem to fully run using a chuffed cpp file instead of flatzinc. There are 2 main commits in this PR that contain two of the solutions I have tried so far. Git commit [Add attempt at creating a problem in wrapper.cpp, update main.rs accordingly](https://github.com/conjure-cp/conjure-oxide/commit/a7c121c2ba125e2594604a310eea260d7e7f4d39) includes my first attempt at getting the XYZ problem to work. This has a build issue that was fixed in the next commit however it contains a different attempt at trying to encode the problem. Specifically, this tries to loop over vec int vars while adding them and using linear to compare the sum to Z, I was told by Nik that this was probably wrong and that just using add should be enough. The next commit is my attempt at this, [Add attempt at fixing wrapper.cpp with exact min and max and using only add](https://github.com/conjure-cp/conjure-oxide/commit/f7523c1e599a239935fb0a7f65dac01a90d2db24). This fixes the build issue and also uses just add with fixed min and max for creatVars. The reason I did this is because I found that the program only crashed when I was equal to 2 in the loop so I thought there must be some kind of off by one error. Making these changes didn't really help though as it still crashes on the same line.

I ran the program through lldb which gave these results.

lldb debugger call stack:
```
1: tid=1957530 "chuffed_rs":
 LinearGE<0, 0>::LinearGE(vec<int>&, vec<IntVar*>&, int, BoolView) linear.cpp:45
 void int_linear<0>(vec<int>&, vec<IntVar*>&, IntRelType, int) linear.cpp:326
 void int_linear<0>(vec<int>&, vec<IntVar*>&, IntRelType, int) linear.cpp:313
 int_linear(vec<int>&, vec<IntVar*>&, IntRelType, int, BoolView) linear.cpp:446
 int_plus(IntVar*, IntVar*, IntVar*) arithmetic.cpp:747
 chuffed_rs::main main.rs:10
```

lldb debugger variables:
```
Local:
 this LinearGE<0, 0> *const = {c:0, fix:0, fix_x:0, fix_y:0, fix_sum:0, ...}
 a vec<int> & = {sz:3, cap:3, data:0x00005555557c4ee0}
 _x vec<IntVar *> & = {sz:3, cap:3, data:0x00005555557c4f00}
   _c int = 0
   _r BoolView = {v:0, s:true}
   i int = 2
```
error description:
```
Description: signal SIGSEGV: address not mapped to object (fault address: 0x0) on line 45 of linear.cpp:
[i]->attach(this, i, EVENT_L);
```

Additionally, I also tried to create x, y and z using just int vars without being a vector but this messes up the branching and output var calls as they expected vec int vars. Obviously given the time constraints I don't think I will be able to fully implement chuffed the same way minion has but I think some progress on this end would still be nice. I plan to create a "lessons learned" type write up for the wiki and for my report as I think this will be useful for the future development of this and other solvers. ~

Any help or suggestions would be greatly appreciated!

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
I found your code didn't build, but once I changed wrapper.h so new_problem and solve used void* instead of Problem*, it worked and produced an answer.

Is it possible you have fixed your problem, but were using an old build? I think one problem with using external libraries is rust isn't good at rebuilding everything when you change files.

Maybe use `git status --ignored` to find everything ignored and make sure you remove everything, then build, fix the issue in wrapper.h I mention above, and see if it works?

**Comment by ChrisJefferson** [comment]
You may want to look into making sure the wrapper is rebuilt if wrapper.h and wrapper.cpp are changed, I think you need something like:

```
    println!("cargo:rerun-if-changed=wrapper.h");
    println!("cargo:rerun-if-changed=wrapper.cpp");
```

in build.rs, near the start of main

**Comment by ozgurakgun** [comment]
thanks @ChrisJefferson! timezone difference is really working to our advantage with this, @Kieranoski702 created the issue late yesterday and I wake up to your messages this morning :)

@Kieranoski702: can you update the PR with Chris's suggestion and let us know if this works for you etc. I have some time today I can try it as well and/or have a chat.

**Comment by niklasdewally** [comment]
> You may want to look into making sure the wrapper is rebuilt if wrapper.h and wrapper.cpp are changed, I think you need something like:
> 
> ```
>     println!("cargo:rerun-if-changed=wrapper.h");
>     println!("cargo:rerun-if-changed=wrapper.cpp");
> ```
> 
> in build.rs, near the start of main

I fixed this as part of #109  hopefully

**Pull request merged**
