### PR TITLE
fix(rules/minion): fix Reduction::new wrong argument order

### PR DESCRIPTION
**Pull request by niklasdewally**
Fixes: #467

### CODE REVIEW

**Comment by ozgurakgun** [comment]
this line wasn't covered and it still isn't, maybe an argument for adding more tests?

https://conjure-cp.github.io/conjure-oxide/coverage/0cd62610eda9c2e553c3ff2b3bf685141a55e772/crates/conjure_core/src/rules/minion.rs.html#194

**Comment by niklasdewally** [comment]
> this line wasn't covered and it still isn't, maybe an argument for adding more tests?
> 
> https://conjure-cp.github.io/conjure-oxide/coverage/0cd62610eda9c2e553c3ff2b3bf685141a55e772/crates/conjure_core/src/rules/minion.rs.html#194

Once I start doing more of the vector operations it will be!

Also need to add some more sum tests to test sum flattening, as I haven't touched sums since last year.

**Comment by ozgurakgun** [comment]
I am not sure why some of those lines are marked as not covered by the way. macros should be marked by default if we could achieve that, and `return Err(RuleNotApplicable);` lines must be covered already unless I am missing something? probably a relic of how coverage is computed.

**Comment by niklasdewally** [comment]
Once that's fixed we should have very good coverage in the minion rules

**Pull request merged**
