### PR TITLE
fully functional, the other extreme

### PR DESCRIPTION
**Pull request by ozgurakgun**
looking for reviews please

### CODE REVIEW

**Comment by ozgurakgun** [comment]
ping @lixitrixi @niklasdewally @ChrisJefferson

**Comment by niklasdewally** [comment]
We are still cloning most things in both, so it shouldn't make too much difference to memory or performance if we do it immutably?

The difference between a short string and an Rc memory wise seems inconsequential too.


If the above is indeed true, it comes down to what is nicest for the programmer. I definitely prefer the look of the second.

**Comment by niklasdewally** [comment]
A semi-related point - if we have lots of nested subexpressions, how do we plan to traverse through them?

The two main ways I can think of are Haskell-style Zippers, and trees made of pointers.  I don't see how either of those can be used in this code. Is there a more idomatic Rust way of doing it, or would we need to adjust our data-structure to allow easier traversal?

**Comment by niklasdewally** [comment]
It might also be the case that we dont need to do zipper style stuff in the first place (i.e. hold a pointer to a particular leaf, and want to be able to go to the next sibling, or to a child, or a parent, etc), which would make the above a moot point

**Comment by ozgurakgun** [comment]
it is a good point. a direct tree-traversal style thing could be a good starting point. I'll push some very concrete examples of this, but we definitely want to build some abstraction around this sort of thing. also, keeping pointers to subtrees and being able to do "rule applications" efficiently will be crucial, so defn related.

**Comment by ozgurakgun** [comment]
pushed something. googling "uniplate for rust" as we speak.

**Comment by niklasdewally** [comment]
What about instead of

```rust
enum Expression {
    ConstantInt(i32),
    Reference(Name),
    Sum(Vec<Expression>),
    Eq(Box<Expression>, Box<Expression>),
    Geq(Box<Expression>, Box<Expression>),
}
```


We do 

```rust
enum Expression {
    Atom(Atomic),
    Sum(Vec<Expression>),
    Eq(Box<Expression>, Box<Expression>),
    Geq(Box<Expression>, Box<Expression>),
}

enum Atomic {
   ConstInt(i64),
   GivenVar(Name),
  SearchVar(Name,
  ...
... 
}

```

**Comment by niklasdewally** [comment]
This would mean that we can do stuff like

Eq(Sum,atomic) = And(Geq(Sum Atomic),Leq(Sum Atomic))

**Comment by niklasdewally** [comment]
(just realised that isnt a great example as b doensnt need to be atomic for that rewriting, but hopefully my point still stands)

**Comment by ozgurakgun** [comment]
not sure if there is a fundemental difference between those, but I am not opposed to it. 

a difference that's important in my experience is between constants/values and expressions. like,  a solution won't have +-*/ in it, and the type system should make that clear.

**Comment by niklasdewally** [comment]
> a difference that's important in my experience is between constants/values and expressions. like, a solution won't have +-*/ in it, and the type system should make that clear.

So, in Rust terms, this?

```rust
enum Expression {
    Literal(Box<Value>),
    Variable(Name),
    Sum(Vec<Expression>),
    Eq(Box<Expression>, Box<Expression>),
    Geq(Box<Expression>, Box<Expression>),
}

enum Value {
   ConstInt(i64),
   List(Box<Vec<Value>>),
  Boolean(bool)
}
```

I was thinking in terms of parsers before where atoms are useful - this is a better way of doing it :)

**Comment by niklasdewally** [comment]
In which case, a solution would just be:

```
struct Solution(Name,Value)

let solutions: Vec<Solution> = .....

```

(or alternatively a hashmap encoding the same information)

**Comment by ozgurakgun** [comment]
exactly. also with things like set literals etc when we get to those.

**Comment by ozgurakgun** [comment]
I guess this isn't immutable - I was thinking functional. maybe... naming is hard.

**Comment by lixitrixi** [comment]
I'm definitely for revisiting how we structure the AST, but I'm not sure about using only string references within the expressions... something about giving the name of the variable to the model to change its domain while traversing the model and not just having the reference right away seems overly complicated, but I agree that Rc<RefCell<... is quite a hack.

**Comment by lixitrixi** [comment]
Should we meet in person sometime this week for an hour to whiteboard this issue?

**Comment by ChrisJefferson** [comment]
I like this general design. I'd probably just make a `VariableStore` up front, and have it have methods for `addVariable(name, domain)`, rather than make a hashMap, just because it makes it easier to add debugging checks (at the moment it would be fairly easy to try to add the same variable twice, which would be a mess, and also it's tricky to create variables using `MachineName`, you'd have to keep track of the number yourself).

**Comment by ChrisJefferson** [comment]
Crazy hypothetical (I have no idea if this is possible in general). Could the AST be typed?

If we have a `BoolExpression` and `IntExpression`, we could stop people adding Bools, or comparing a Bool with an Int for equality. I don't know if this is sensible, or if it would scale well.

**Comment by ozgurakgun** [comment]
It isn't crazy, see GADTs in Haskell. But I found them to be too strict in Conjure. Especially when implementing generic traversals. So I am tempted to have a single expression type initially with dynamic type checking, we could potentially refine it later. Happy to be convinced otherwise though. I have been looking into existing syntax manipulation libraries in rust since yesterday. There are some, though I still don't fully grok what they offer.

**Comment by niklasdewally** [comment]
I guess this is more related to the later concern of how do we represent a model for a solver that only support a subset of this AST.

In particular, if each solver.have all its own types which then get translated to/from the higher level, the above is irrelevant

**Comment by ChrisJefferson** [comment]
I would personally plan on each solver having it's own crate (solvers in a common family might share a crate -- the most obvious example would be SAT solvers with a similar interface, might all share a crate).

I suspect each solver is probably going to have it's own AST -- there just aren't enough similarities. There might want to be some kind of common 'options' object (for example), and solution return, which might want to be shared between all crates (which as you say, could produce a loop). That "common base" could be in it's own crate.

This is just all guessing of course.

**Comment by ozgurakgun** [comment]
The solvers bindings shouldn't depend on conjure-oxide. They should just expose the functionality offered by the solver, but in rust. They will have whatever API/data structure that makes sense for that solver at this level.

We will probably implement higher level helper functions for each solver, with enough abstraction among solvers where sensible.

Regarding language: one clunky option would be using the same data structures, but making sure we do not use anything that's not supported by the solver. This can be checked dynamically (at runtime).

Another clunky option is duplicating the supported subset of the language for each solver. This sounds like more work, but could be fine.

I am sure there are more advanced ways of handling this kind of thing (search for the expression problem, GADTs, tagless g-machine to start going down the rabbit hole). I am not worried about this at this point at all, would be happy with a single language data structure and dynamic checks to start with.

**Comment by niklasdewally** [comment]
> would be happy with a single language data structure and dynamic checks to start with.

Me and Felix had differing opinions on this today, Ive summarised them below:

> A: Regarding language: one clunky option would be using the same data structures, but making sure we do not use anything that's not supported by the solver. This can be checked dynamically (at runtime).

>B:  Another clunky option is duplicating the supported subset of the language for each solver. This sounds like more work, but could be fine.


The advantages/disadvantages of these as I see it are as follows:

### A
Advantage: Less boilerplate / duplicated datatypes between. 
Advantage: The callback function logic  and solver adaptor interfaces could be easier,  as callback functions would all be of type:
```
function callBack(sols: Solutions) {

}
``` 

instead of relying on some solver specific solution type( I call T).

```
function callBack<T>(sols: T) {

}
```

Disadvantage: AST needs to be in its own crate, and so will be a public API and harder to change.
Disadvantage: Would not work for solvers that have model ASTs radically different from the Conjure one.

### B

Advantage: AST is a private datatype so can be changed whenever needed for tailor logic. 
Disadvantage: Would need extra layers of code just for translating types for models or solutions, even if those types are almost identical!


-----
I'm thinking the current flow, similar to B:

image

Where translate does translations between the private conjure::ast and the ast for a specific solver. And in reverse for getting solutions out.

We could make things slightly less boilerplatey on the solver side of things by making the AST and datatypes in a "common stuff" crate anyways. For solvers that want to use this, Translate would go from conjure::ast -> conjure::ast, which is just the identity.

**Comment by niklasdewally** [comment]
Felix is now for translate, but we are both still unsure how to proceed with this

**Comment by ozgurakgun** [comment]
Feel free to make a decision and experiment! We can't be scared of refactoring this early in the project :)

**Comment by ChrisJefferson** [comment]
Here is a suggestion on how to call solvers, feel free to think this is too complicated :)

I think that the callback might want to get multiple pieces of information (the solution, the node count, the optimisation value), and the info might grow over time. Assembling all that stuff is a big struct, and also has the disadvantage that it's a waste if people don't want all of it.

Therefore, instead we make the callback just be given a struct, which has methods on it. Something like this perhaps?

Firstly, we define a general solver, then implement it for a given solver. Note that I make `MinionCallback` private, as no-one should ever be able to create an actual instance of this object themselves.

```
pub trait SolverCallback {
    fn node_count(&self) -> u64;
    fn memory_usage(&self) -> u64;
    fn solution(&self) -> Vec<u64>;
}

struct MinionCallback {}

impl MinionCallback {
    fn new() -> MinionCallback { MinionCallback{} }
}

impl SolverCallback for MinionCallback {
    fn node_count(&self) -> u64 { 1 }
    fn memory_usage(&self) -> u64 { 100 }
    fn solution(&self) -> Vec<u64> { vec![1,2,3] }
}
```

Then we make a function which calls the solver (obviously in practice this would call into minion, and the user's callback would only get executed when the solver finds solutions, and the `MinionCallback` would actually do useful things:

```
pub fn run_minion(f: &dyn Fn(&dyn SolverCallback) -> bool ) {
    let mc = MinionCallback::new();
    f(&mc);
    f(&mc);
}
```

Then you actually use this like this:

```
use callbackexample::callback::{run_solver,SolverCallback};

fn main() {
    let callback = |sc: &dyn SolverCallback| { println!("nodes: {}", sc.node_count()); true };
    run_solver(&callback);
}
```

In terms of what should be in the `minion` crate, I would suggest (but this is open for debate!) it should be the least amount of code required to make a safe interface -- so no-one using the `minion` crate should have to use `unsafe` (well, you might make some super-special highly efficient interface that uses unsafe, but that should be the standard behaviour).

**Comment by ChrisJefferson** [comment]
Two extra suggestions -- "Documentation Driven Development" -- when designing an API, I have in the past found it useful to write out some basic docs and examples first. In particular, if you find yourself writing things like "do not call X before Y", then you know you've probably made a mistake :)

Also, when returning a solution, I'd recommend planning on just returning a single list (minion currently stores solutions as a matrix, just because that's natural for printing). You could just drop the whole "print" part of the interface, just return assignments to all variables, and make a hashmap or some such?

**Comment by ozgurakgun** [comment]
about the actual PR, did anyone hate the final version? can we merge it?

**Comment by lixitrixi** [comment]
I think this is good to merge! Once it is I'll do my refactoring

**Pull request merged**
