### PR TITLE
Complete code coverage CI

### PR DESCRIPTION
**Pull request by niklasdewally**
Screenshot 2024-02-11 at 01 44 14

### CODE REVIEW

**Comment by ozgurakgun** [comment]
nice!

I guess it is not exactly comparing code coverage before/after this PR. Instead if is this PR vs main, which could have moved on with other commits. Though that can be remedied by merging main into this PR.

is there a similar textual summary for the doc doverage? it's hard to say what I'll see if I were to expand those triangles in the screenshot.

**Comment by niklasdewally** [comment]
> is there a similar textual summary for the doc doverage?

It's the full coverage report at the moment. There are no actions that do rustdoc stuff (that work), so I'm rather limited. 

Rustdoc can output coverage as JSON, but there are no tools on the internet that can format this nicely yet/total these up. It will need some playing around with jq to get looking nice.

**Comment by niklasdewally** [comment]
> Instead if is this PR vs main, which could have moved on with other commits.

All the other actions actually run in the context of "what happened if we merged this into main now", so it would be consistent in that regard. Not quite sure how to word this though....

**Comment by niklasdewally** [comment]
https://github.com/niklasdewally/conjure-oxide/pull/1

@ozgurakgun 

I'm not happy with the output for docs, but I think it will take some work to make better...

**Comment by niklasdewally** [comment]
Looking at my vip backlog, I have a lot of Minion stuff that needs doing soon. So, I think if this works (even if it's a bit ugly), it would be best to be merged and revisited later / by someone else?



I will document the wiki soon with high level details and GitHub actions gotchas, so that it is easier for someone else to take over this. I'll also put the command to generate the doc coverage JSON in there, as it's a bit of a hidden scarcely used feature.

**Review by ozgurakgun — APPROVED** [review]

**Comment by niklasdewally** [comment]
https://github.com/conjure-cp/conjure-oxide/wiki/Coverage
https://github.com/conjure-cp/conjure-oxide/wiki/Github-Actions:-Cookbook

**Pull request merged**
