### PR TITLE
Rules to convert logical expressions to CNF (Issue 152)

### PR DESCRIPTION
**Pull request by gskorokhod**
Basic rules to simplify logical expressions (e.g. unwrap nested AND and nested OR, distribute NOT over an expression, etc)

See: #152 

**Depends on PR #83**

### CODE REVIEW

**Comment by gskorokhod** [comment]
This is not ready to merge yet, just putting it out there :)

**Comment by gskorokhod** [comment]
One problem I've encountered so far is this:

This [thread](https://math.stackexchange.com/questions/214338/how-to-convert-to-conjunctive-normal-form) suggests using distributive laws:

1. (P⋁(Q⋀R))↔(P⋁Q)⋀(P⋁R)

2. (P⋀(Q⋁R))↔(P⋀Q)⋁(P⋀R)

However, these would cause a loop (see attached image)

image

Not sure what to do about this yet..

**Comment by ozgurakgun** [comment]
I like the look of these rules! We can talk about the looping behaviour.

**Comment by gskorokhod** [comment]
I think that's it in terms of rules actually!
(I have De Morgan's Law and one of the 2 distributive rules)

Might be better to wait for Kieran's PR to get merged, then rebase and test the rules before we merge though?

**Pull request merged**
