### PR TITLE
tester: run minion and print progress for debugging

### PR DESCRIPTION
**Pull request by niklasdewally**

### CODE REVIEW

**Comment by niklasdewally** [comment]
@ozgurakgun is this ready to merge?

**Comment by ozgurakgun** [comment]
not sure if we should with failing test cases. it'll be hard to keep track of why the tests are failing going forward. how hard would it be to make these work? alternatively we can temporarily remove the failing integration tests.

**Comment by niklasdewally** [comment]
> not sure if we should with failing test cases. it'll be hard to keep track of why the tests are failing going forward. how hard would it be to make these work? alternatively we can temporarily remove the failing integration tests.

Basically just need minion constraints. The NotSupported thrown seems to be either from the solver interface or minion_rs.

**Comment by niklasdewally** [comment]
I can either remove the tests for now, or I could rebase #219 on top of this branch, and merge that when i implement the functions for these tests.

**Comment by niklasdewally** [comment]
Do we have a mechanism for disabling integration tests (aside from just deleting them)?

**Comment by niklasdewally** [comment]
@ozgurakgun disabled some tests. should be fixed when i add the constraints though

**Pull request merged**
