### PR TITLE
introduce a install-conjure action

### PR DESCRIPTION
**Pull request by niklasdewally**

### CODE REVIEW

**Comment by ozgurakgun** [comment]
I think it's better if we were consistent with the matrix args style of this action: https://github.com/conjure-cp/conjure-oxide/blob/main/.github/workflows/test.yml#L33

That way we can test with multiple conjure versions at once, which might be nice in the future.

**Comment by niklasdewally** [comment]
will do - good idea.

I just also found out that theres a github actions LSP server, so hopefully I can syntax check these locally from now on...

**Comment by ozgurakgun** [comment]
I used the vs code plugin when I was touching these last time, worked ok.

**Comment by ozgurakgun** [comment]
> i don't know how we will store the different versions of coverage made by these

good point! we probably won't have multiple conjure versions for this ever then, but still we could stick to the matrix syntax unless there is a reason not to? 

maybe also write a short comment capturing this?

**Comment by niklasdewally** [comment]
> > i don't know how we will store the different versions of coverage made by these
> 
> good point! we probably won't have multiple conjure versions for this ever then, but still we could stick to the matrix syntax unless there is a reason not to? 
> 
> maybe also write a short comment capturing this?

A better, not that much harder way to get consistent syntax, would be to refactor out "install conjure" as it's own workflow we can import and use. Shouldn't be too hard.

**Comment by niklasdewally** [comment]
I think the proper terminology is "create our own action"

**Comment by niklasdewally** [comment]
@ozgurakgun found another conjure-oxide

**Comment by niklasdewally** [comment]
@ozgurakgun seems good now

**Comment by ozgurakgun** [comment]
kudos, good debugging there. I'll squash merge?

**Pull request merged**
