### PR TITLE
Fix code coverage

### PR DESCRIPTION
**Pull request by niklasdewally**
Issue seems to be that workflow run uses the sha of last commit on main, not sha of the pr we want coverage for.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run

Fixing this

### CODE REVIEW

**Comment by niklasdewally** [comment]
Potential fix for #48 #38

**Comment by niklasdewally** [comment]
@ozgurakgun this should work now. I have tested it on my fork, but might be good to merge then this on a real-life PR here too.

Also renamed latest to main

**Comment by niklasdewally** [comment]
(Deploy still shows as failed in actions, as the deploy workflow always runs the version of itself that is currently in main)

**Comment by ozgurakgun** [comment]
I think this calls for either writing some comments in the workflows and/or a description in the wiki. Given that it is far from trivial!

I'll merge this one now so we can test on #46.

**Comment by niklasdewally** [comment]
Some docs here
https://github.com/conjure-cp/conjure-oxide/wiki/Github-Actions#writing-actions-involving-prs-a-caution

**Pull request merged**
