### PR TITLE
initial implementation of generic tree reduction library

### PR DESCRIPTION
**Pull request by lixitrixi**
This is intended to be a possible project for the VIP!

The main idea is to abstract the reduction rule system into a powerful engine acting on generic Uniplate types. The main access point is the function `reduce`, which accepts a list of rules, a tree, and some metadata.

Rules must support a function which, given some subtree and some persistent metadata, returns either a new subtree to replace the given one, or some error. Errors may simply mean "Not Applicable", or could even do some optimisation by pruning the entire subtree from the engine's traversal. Side effects such as adding top-level constraints and rewriting the metadata are contained in a Command Pattern, and are applied if and after the whole tree is rewritten with a rule's returned subtree.

Currently the library doesn't support what we need in Conjure Oxide: (1) rewrite selection and (2) dirty-clean optimisation. These might be implemented in the following ways:

1. Rewrite selection might be added by allowing the user to pass some function `(Iter<(Rule, SubTree)>) -> Option<SubTree>` or similar. The use of an iterator makes it more efficient by lazily evaluating rule reductions, but also opens up problems with how to deal with rules returning "Prune" or "Ignore" errors in the middle of the iteration. If a rule says to ignore the whole subtree, should we discard the user's choice of rewrite?
2. Instead of dealing with the types directly, the tree could be wrapped inside another tree type which provides additional metadata for optimisation.

### CODE REVIEW

**Comment by ozgurakgun** [comment]
Hi @lixitrixi - as we discusssed earlier I am keen to try this. It would be good if you constructed a few examples, maybe as doctests, and I can give you a few more challenge test cases to test the kinds of features we will need. You can use the calculator language (with statements to be sure of the biplate behaviour) for the tests: https://crates.io/crates/uniplate

**Comment by ozgurakgun** [comment]
We talked about this today during the drop in session and I encouraged people to bug you about adding that concrete example, or helping others add it. Consider yourself warned :)

**Comment by lixitrixi** [comment]
> Hi @lixitrixi - as we discusssed earlier I am keen to try this. It would be good if you constructed a few examples, maybe as doctests, and I can give you a few more challenge test cases to test the kinds of features we will need. You can use the calculator language (with statements to be sure of the biplate behaviour) for the tests: https://crates.io/crates/uniplate

Absolutely! I will do this before our meeting tomorrow.

**Comment by ozgurakgun** [comment]
having a generic tree rewriting library that builds on top of uniplate sounds like a good idea to me. but gen_reduce isn't the best name you will agree. have been thinking: spell? as in spellcasting. or alchemy, all about transformation? 

oh apparently grimoire means "A textbook of magic, typically including instructions on how to create magical objects" according to wikipedia. each rule can be a spell and the whole ruleset is a grimoire. I'll stop there...

**Comment by YehorBoiar** [comment]
I finally can understand what this PR is about! Great documentation, @lixitrixi!
I like the idea of creating a separate library. Can I start contributing to this project, @lixitrixi?

**Comment by lixitrixi** [comment]
> I finally can understand what this PR is about! Great documentation, @lixitrixi!
> 
> I like the idea of creating a separate library. Can I start contributing to this project, @lixitrixi? 

Absolutely!!! I'll also be contributing a bit over reading week (not much to do on the plane). Would you be able to meet virtually tomorrow to split up some of the tasks?

**Comment by YehorBoiar** [comment]
Hey! I'm not gonna be in St Andrews by tommorow afternoon. Can we do tommorow morning? (Like 9-10AM or 10-11AM)

**Comment by lixitrixi** [comment]
> having a generic tree rewriting library that builds on top of uniplate sounds like a good idea to me. but gen_reduce isn't the best name you will agree. have been thinking: spell? as in spellcasting. or alchemy, all about transformation?
> 
> oh apparently grimoire means "A textbook of magic, typically including instructions on how to create magical objects" according to wikipedia. each rule can be a spell and the whole ruleset is a grimoire. I'll stop there...

I like this direction :0

Unfortunately grimoire is taken... how about "thaum" for thaumaturgy?

**Comment by ozgurakgun** [comment]
I won't veto thaum :)

**Review by YehorBoiar — APPROVED** [review]

**Comment by lixitrixi** [comment]
@YehorBoiar I think force-pushing to a collaborative branch is generally a bad idea... @ozgurakgun what's the best way to collaborate in this case? Should I just give Yehor access to my branch? Should we make a separate repo now?

**Comment by lixitrixi** [comment]
No worries at all! I thought it was just a test. I think it should be fine to just develop by pushing to this branch, so keep doin what you're doin B)

**Comment by YehorBoiar** [comment]
I am not sure if pushing on this branch would be the best. I think having a PR would make it easier for us to callaborate as I would be able to push some experimental changes, or broken code that I need to fix without braking your code.

**Comment by YehorBoiar** [comment]
I'm just writing pseudocode for now, so free to push!

**Comment by lixitrixi** [comment]
For reference, more discussion going on here: https://github.com/lixitrixi/conjure-oxide/pull/2#issuecomment-2450503092

Is it possible to make PRs to the branch on this repository instead? I know that PRs form a branch under the hood, so could you technically make a PR to a PR?

**Comment by YehorBoiar** [comment]
I made a PR on your branch, so when we would merge that PR, this PR would also get updated

**Comment by YehorBoiar** [comment]
@lixitrixi You mentioned that you would push some change that would affect my clean/dirty implementation. Should I wait untill your push?

**Comment by lixitrixi** [comment]
If you have an implementation in mind please go ahead!

**Review by ozgurakgun — APPROVED** [review]

**Comment by ozgurakgun** [comment]
yep, happy to merge. you don't want to rename before we merge?

**Comment by ozgurakgun** [comment]
tree-morph? not magical, but descriptive.

**Comment by lixitrixi** [comment]
Absolutely. `treemorph` or `tree-morph`?

**Comment by ozgurakgun** [comment]
quick browse on https://crates.io and people tend to use kebab case for crate names. so I would vote for with tree-morph.

**Pull request merged**
