### PR TITLE
Specify solver imports explicitly

### PR DESCRIPTION
**Pull request by lixitrixi**

### CODE REVIEW

**Comment by ozgurakgun** [comment]
github actions are not triggered on this, since it doesn't edit the relevant paths. makes me think we should list Cargo.toml and Cargo.lock in the paths section of all 3 tests, since it would be good to trigger them when these files change. does that make sense?

**Comment by lixitrixi** [comment]
> github actions are not triggered on this, since the PR doesn't modify any files stored at the relevant paths. makes me think we should list Cargo.toml and Cargo.lock in the paths section of all 3 tests, since it would be good to trigger them when these files change. does that make sense?

Heard!

Should it be a separate PR?

**Comment by ozgurakgun** [comment]
I am no fussed, let's add onto this one.

**Comment by lixitrixi** [comment]
@ozgurakgun This should be good to go now

**Pull request merged**
