### PR TITLE
Bubble exprs

### LINKED ISSUE #246: Bubble expression variant
This type of expression is necessary for many things as we move forward, including division. This should be implemented along with expression types and reductions to test the correct functionality.

Basically, a Bubble is an expression which says "x is valid as long as y is true". For example...
```text
x / y = z
```
... can be re-written as:
```text
x / y = z /\ y != 0
```

This is done by replacing the `x/y` expr with a bubble: `((x / y) @ (y != 0)) = z`.
The bubble is "bubbled up" to the `=` expression above: `((x / y) = z) @ (y != 0)`
Since we are now in a boolean context (i.e. the expression return type is a boolean), we can replace the bubble with a conjunction to give the final expression above.

<hr>

### Goals

- [ ] Add Bubble expression variant
- [ ] Add rules to bubble up and expand bubbles
- [ ] Implement division

I'll be adding intermediate goals here as I go along.

### PR DESCRIPTION
**Pull request by lixitrixi**
Here I add Bubble expressions as well as Div and SafeDiv (which depend on bubbles). See #246 for more information on this expression variant.

This closes #246

### CODE REVIEW

**Comment by lixitrixi** [comment]
@ozgurakgun I'm trying to figure out how to represent/implement types. I don't want to add another Enum as we already have Constant, which represents all the types we currently have. On a practical level, what is a type?

I'm thinking one way could be:
```rust
type ReturnType = fn(_) -> Constant
```
As we can then deal in Constant constructors with little fuss, e.g. `if matches!(Constant::Int, expr.return_type())`. It's just an issue of fighting with the compiler to let us pass arbitrary enum constructors around.

**Comment by lixitrixi** [comment]
Or, alternately, we could return `bool` and `i32` directly... This seems to run into the same problems as the above with incompatible types though.

**Comment by lixitrixi** [comment]
We can use the enum discriminants! I will investigate :)

**Comment by ozgurakgun** [comment]
I think we do need another enum for types actually.

**Comment by lixitrixi** [comment]
> I think we do need another enum for types actually. 

Would it be Int and Bool for now?

**Comment by ozgurakgun** [comment]
Yes! Likely to grow into something like this in the fullness of time: https://github.com/conjure-cp/conjure/blob/951e2d738a7b70fe1606112292a44b3382d12a48/src/Conjure/Language/Type.hs#L28

**Comment by lixitrixi** [comment]
@ozgurakgun how are multiple bubble expressions bubbled up at once? E.g. if an expr has 2 bubble children. I assume the conditions are "conjuncted"

**Comment by lixitrixi** [comment]
To be able to support things like Leq with division, we need to use the same method of creating a new variable as we did for Min. I'm currently working on this but it may mess some things up with Div

**Comment by ozgurakgun** [comment]
not sure what you mean with <=.

would it not be something like the following?

```
a <= b/c
a <= { safediv(b,c) @ c!= 0}
{a <= safediv(b,c) @ c!= 0}
a <= safediv(b,c) /\ c!= 0
```

**Comment by lixitrixi** [comment]
> not sure what you mean with <=.
> 
> would it not be something like the following?
> 
> ```
> a <= b/c
> a <= { safediv(b,c) @ c!= 0}
> {a <= safediv(b,c) @ c!= 0}
> a <= safediv(b,c) /\ c!= 0
> ```

Sorry for the late response! I'm working on this tonight and tomorrow.

I was mainly talking about giving division problems to Minion. It only supports the Conjure Oxide constraint `DivEq`, so we have to use the same method as with `Min` to create an intermediary variable we can then use with different operations.

**Comment by lixitrixi** [comment]
@ozgurakgun I've currently disabled test case div-4, as certain rules which are necessary to convert to minion are being implicitly given a higher priority as they are applicable higher up the tree.

Case div-4 does rewrite correctly according to the eq/neq semantics we discussed (i.e. not treating them the same), but the final model has `Not` expressions which I can't figure out how to apply currently without the problems above interfering.

In any case, this PR is now (finally) in a state to be merged, closing #246.

**Comment by ozgurakgun** [comment]
what's the problem with div-4, sorry? we can change rule precedences if there is a good reason to do so.

not handling div-4 might mean we are missing something fundemental.

**Comment by lixitrixi** [comment]
@ozgurakgun This is good to merge whenever you want to; I will be making the bound fixes over at #294 since they are outside of the scope of this PR.

**Pull request merged**
