### PR TITLE
Workspace refactor

### PR DESCRIPTION
**Pull request by lixitrixi**

### CODE REVIEW

**Comment by lixitrixi** [comment]
Here I separate conjure_oxide into its own package within the workspace and clean up the package structure slightly.

**Comment by lixitrixi** [comment]
Not sure where the parsers directory commit comes from... Probably accidentally added to my fork's main at some point.

I will also try to set conjure as the default package to run.

**Comment by niklasdewally** [comment]
Might need some CI path changes (feel free to move this to a separate issue)
- gen_coverage_all.sh
- codecoveage.yml (line 69)
- doc-coverage.yml 
- build test

**Comment by niklasdewally** [comment]
(We could always do this after #32 is done)

**Comment by ozgurakgun** [comment]
ok, this looks fine but I am slightly confused about the relationship between this and #32. is this ready to go? will 32 continue after this is merged?

**Comment by niklasdewally** [comment]
> ok, this looks fine but I am slightly confused about the relationship between this and #32. is this ready to go? will 32 continue after this is merged?


It's unrelated. There's some ci refactoring to do here before merge

**Comment by niklasdewally** [comment]
(just minor path fixes, shouldn't take long.)

**Comment by niklasdewally** [comment]
Fixed the CI paths as said above in #54.

(it is based on this branch, so this one needs merging first)

**Comment by ozgurakgun** [comment]
I can merge this and #54 is everyone is happy?

**Pull request merged**
