### PR TITLE
Model example library for testing

### PR DESCRIPTION
**Pull request by PedroGGBM**
Original issue #65:

The minion bindings should have fully runnable and testable documentation examples.

As suggested by Chris Jefferson, having a library of example models would cut down on code duplication in these doctests.

This should take the form of a public module inside the crate with functions such as:

```
examples::bibd_model()
examples::xyz_model()
```

This should be used to rewrite the example for the callback type. This example needn't include details of model construction (it is primarily concerned with how you print the results at the end) , so it is an ideal candidate for using an example model.

Also potentially add some model building shortcut functions, such as making n variables of domain 0..m..

### CODE REVIEW

**Comment by lixitrixi** [comment]
Just wanted to add what we discussed today and submit it to peer review:

I was thinking a clean way to approach this "example registry" would be with a `get_example_model` function, which accepts a string, loads the corresponding `.essence` file from a hard-coded directory, parses it through conjure/json, and returns it, rather than hard-coded example constants.

This would mean we can create examples before/while adding support for certain AST variants. It would also force us to implement the parser for each new AST extension ASAP, which I personally think is a good thing.

@ozgurakgun what do you think?

**Comment by ozgurakgun** [comment]
Great idea! It'll make adding new examples a lot easier.

**Comment by ozgurakgun** [comment]
That doc coverage table is begging for a summary Pedro :)

**Comment by lixitrixi** [comment]
CI is failing because of the following error:

```Unhandled error: HttpError: Resource not accessible by integration```

This seems to be a CI issue? Not sure what's going on. @niklasdewally

**Comment by niklasdewally** [comment]
> CI is failing because of the following error:
> 
> ```Unhandled error: HttpError: Resource not accessible by integration```
> 
> This seems to be a CI issue? Not sure what's going on. @niklasdewally 

Already discussed this with @PedroGGBM over teams - there seems to be a duplicate version of the "code and documentation coverage" ci in this PR from when Pedro was experimenting with it.

@PedroGGBM if you just delete the yaml file of the broken workflow it should just disappear.

**Comment by ozgurakgun** [comment]
rm the conjure-output folder

**Pull request merged**
