### PR TITLE
using a matrix configuration for github actions

### PR DESCRIPTION
**Pull request by ozgurakgun**
using a matrix configuration for github actions, just edited one of the actions for now

### CODE REVIEW

**Comment by ozgurakgun** [comment]
If I am getting this right, we either test `rustup target add aarch64-apple-darwin` and won't run the tests on macOS, or we remove that (stick to macos-intel) and test on both linux and mac. Is that right @niklasdewally ?

I hear github will soon start offering arm macos runners. Until then we could just test on macos-intel? Given that enough of us are locally using arm macs, this could be a better trade-off?

**Comment by niklasdewally** [comment]
> If I am getting this right, we either test `rustup target add aarch64-apple-darwin` and won't run the tests on macOS, or we remove that (stick to macos-intel) and test on both linux and mac. Is that right @niklasdewally ?
> 
> I hear github will soon start offering arm macos runners. Until then we could just test on macos-intel? Given that enough of us are locally using arm macs, this could be a better trade-off?

I added that for cross compilation from whatever tutorial I used, but I don't think it's actually doing anything?

**Comment by niklasdewally** [comment]
In short , I don't think the arm stuff ever worked, so Intel's fine :)

**Comment by ozgurakgun** [comment]
ok, I'll use this to try to debug the cache misses. will edit the other actions to use matrices aftet that.

**Comment by ozgurakgun** [comment]
cache behaviour fixed now. had nothing to do with keys, had everything to do with yaml: https://github.com/conjure-cp/conjure-oxide/pull/102/commits/d622a501fccf3000de2060120ed42040aa0361cb

**Comment by niklasdewally** [comment]
> cache behaviour fixed now. had nothing to do with keys, had everything to do with yaml: [d622a50](https://github.com/conjure-cp/conjure-oxide/commit/d622a501fccf3000de2060120ed42040aa0361cb)

Thank you for spotting this needle in a haystack!

I am surprised GHS yaml validator didn't catch this (it is syntactically invalid in this form),  but its yaml so I am not that surprised....

**Comment by ozgurakgun** [comment]
why the heck did this start failing??? conjure is in path, but cargo still picks up the dreaded imagemagick one.

**Comment by ozgurakgun** [comment]
fixed eventually, it was $HOME vs ~

**Pull request merged**
