### PR TITLE
CI: Code Coverage

### PR DESCRIPTION
**Pull request by niklasdewally**
This PR adds code coverage reports for cargo test.

### CODE REVIEW

**Comment by niklasdewally** [comment]
@ozgurakgun I have added on this branch a gen_coverage script.

What do you think of the html output of this?

**Comment by niklasdewally** [comment]
VSCode can also read the generated lcov file with the right extensions

https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters

**Comment by niklasdewally** [comment]
When I deploy these to github pages, should I keep project coverage reports as part of this repo's pages, or create a new repository just for coverage reports (as you have done for conjure)?

**Comment by ozgurakgun** [comment]
I say just on the gh-pages for this repo.

Now sure if we need this to be a cron job? Just run on all commits to main and for PRs?

**Comment by niklasdewally** [comment]
It will not work here until merged but I have it working in a local fork.

See:
https://niklasdewally.github.io/conjure-oxide/coverage/latest/conjure-oxide/
https://niklasdewally.github.io/conjure-oxide/coverage/latest/minion/
https://niklasdewally.github.io/conjure-oxide/coverage/latest/chuffed/

The action summary has a link to the coverage reports for that particular commit.

The coverage reports for commits to main are also copied to /latest. This will allow the use of auto-updating badges, e.g.

**Comment by niklasdewally** [comment]
It will not work here until merged but I have it working in a local fork.

See:
https://niklasdewally.github.io/conjure-oxide/coverage/48e253498606779a69631493937cb3b8c3593809/conjure-oxide/
https://niklasdewally.github.io/conjure-oxide/coverage/48e253498606779a69631493937cb3b8c3593809/minion/
https://niklasdewally.github.io/conjure-oxide/coverage/48e253498606779a69631493937cb3b8c3593809/chuffed/

The coverage reports for commits to main are also copied to /latest. This will allow the use of auto-updating badges, e.g.



---

In the action summary, I list:

code coverage badge for each crate for this commit.
code coverage url for each crate for this commit.

code coverage badge for each crate at latest main.
code coverage url for each crate at latest main.

Hopefully this would allow better "at a glance" comparisons of coverage.

**Comment by niklasdewally** [comment]
@ozgurakgun I think this is ready for review

**Comment by ozgurakgun** [comment]
Looks good to me! Did you intend this to be squash merged or do you care about maintaining the history (in which case we might want to rewrite history before merging)?

**Comment by niklasdewally** [comment]
> Looks good to me! Did you intend this to be squash merged or do you care about maintaining the history (in which case we might want to rewrite history before merging)?

A squash merge would be appreciated

**Pull request merged**
