### PR TITLE
ran it thorough a YAML validator this time...

### PR DESCRIPTION
**Pull request by ozgurakgun**

### CODE REVIEW

**Comment by ozgurakgun** [comment]
This is tricky to check before it lands on main because depenadbot won't run on PRs.

https://github.com/dependabot/dependabot-core/issues/4605

**Comment by niklasdewally** [comment]
While you are fixing yaml here
    workflows: [code-coverage]

should be

    workflows: ["Code Coverage (Generate)"]


at the top of the code-coverage-deploy

**Comment by niklasdewally** [comment]
As this runs on main it is also very hard to test ....

**Comment by ChrisJefferson** [comment]
One general github suggestion -- when you need to test things like this, do it on your own fork's main branch, as at least then you aren't creating lots of churn other people have to see, and can also force-push to your own main.

**Pull request merged**
