### PR TITLE
Rule Engine

### LINKED ISSUE #96: Representing Rewrite Rules, and Basic Rewriting Engine
Details TBC, but some stuff about this is in the [High level plan](https://github.com/conjure-cp/conjure-oxide/wiki/High-Level-Plan).

### PR DESCRIPTION
**Pull request by niklasdewally**
Pair-programming with Felix, will close #96.

(Mostly Felix now, as I have not yet finished my logic practical!)

### CODE REVIEW

**Comment by niklasdewally** [comment]
Felix has some nice macro ideas currently in progress that turn this into a struct Rule with name this_rule, and registers this as a Horizontal and puts it in the Horizontal list

**Comment by niklasdewally** [comment]
To give an update:

the rule macro above a function creates a rule with the given type, a name equal the name of the function, and sets the "application" field of the rule to the function the macro is above.

Felix is planning to create a global rule registry, using the `linkme` crate, but for now we are just printing out the rule we generate at the top of main.rs.

While rules will be in their own files soon, at the moment we have defined one inside main, as the macro contains println!s for testing.

**Comment by niklasdewally** [comment]
```
    #[rule(Horizontal)]
    fn example_rule(expr: Expression) -> RuleApplicationResult {
        Err(RuleApplicationError::RuleNotApplicable)
    }
```

is turned into a Rule struct.
This looks like so on a debug print:

```
Rule { name: "example_rule", kind: Horizontal, application: 0x104e0422c }
```

**Comment by niklasdewally** [comment]
Felix has seemed to also been summarising our coding session in #96

**Comment by ChrisJefferson** [comment]
This seems like a reasonable direction -- I think this is an area where it's worth exploring.

With regards rule application, my temptation (but Ozgur might have a much better opinion!) would be to have some very simple type of matching (maybe just the type of the top level node) which can be done before the rule (this will let us avoid invoking most rules on most nodes), then the rule can still do arbitary, more advanced, rejection where required.

**Comment by ozgurakgun** [comment]
I had a very brief chat with @lixitrixi earlier today about this. Normally it would be good to go over this together before merging, but that may not be possible given the semester break. I'll leave this to your judgement for now and will merge after a light review when you are happy with it (if you like). We can go through it in the new semester and talk about some of the trade-offs.

**Comment by ChrisJefferson** [comment]
Is there any tests? I was trying to look through for how to use the rules, and check they basically work.

**Comment by niklasdewally** [comment]
> Is there any tests? I was trying to look through for how to use the rules, and check they basically work.

I added a doc test for showing how to represent them.

At the moment if you cargo run conjure_oxide, it will print out the struct representation of a macro generated rule.

**Comment by niklasdewally** [comment]
(This is why the rule is written inside main(), not in its own file - its currently just passing the expanded rule to println())

**Comment by niklasdewally** [comment]
Jotting down an idea from a random conversation with @lixitrixi:

We currently have imperative definition of rules (a Rust function), not declarative ones (pattern-matching essence expressions). However, declarative rule definitions can be added on top of this imperative definition without any modification.

Declarative rules could be defined as a macro which compiles some DSL down to a Rust function that performs the transformation described. This Rust function would then be stored in Rule as we already do here.

**Comment by niklasdewally** [comment]
Work on this is now in #137 and #141

**Pull request closed without merging**
