### PR TITLE
Add test that checks if the write function can simplify the xyz problem

### PR DESCRIPTION
**Pull request by Kieranoski702**
Just a small PR that adds a test for the rewrite function using the xyz problem which has been made into a nested expression compared to previous tests. 

My only question, before I think this is ready to merge, is whether I should add an assert that checks whether the rewritten expression is in the "simplest form". My reason for not including one was that I believe the simplest expression will change over time as we add more rules so this will have to be updated constantly but honestly, I am not sure how true this is as I have not been working on the actual rules themselves. Could someone closer to the work on rules let me know if an assert should be added?

### CODE REVIEW

**Comment by ozgurakgun** [comment]
the simplest form check can be something like: check all nodes of the ast and make sure no rules are applicable for any of the nodes.

**Comment by Kieranoski702** [comment]
> the simplest form check can be something like: check all nodes of the ast and make sure no rules are applicable for any of the nodes.

That's a good idea thank you! I'll add that in

**Comment by Kieranoski702** [comment]
Just thinking about this more. Wouldn't this just be the same as calling rewrite again on the expression and making sure it hasn't changed? Obviously using `rewrite` to test if `rewrite` is working isn't good but if I were to implement a new function to check the simplest form I would essentially just be writing part of `rewrite` again. Not sure what to do here!

**Comment by Kieranoski702** [comment]
In order to test if an expression tree is in its simplest form I have created the is_simple function which is just a copy of the current rewriter code. When the rewriter becomes more complex this code should still check for the simplest form in an easy to understand and less complex way. This is a bit crude and I am not in love with this solution so if people can think of a better way to test this then please let me know.

I think for now at least this PR is ready to be merged in @ozgurakgun

**Pull request merged**
