### PR TITLE
CI: Pretty print documentation coverage

### PR DESCRIPTION
**Pull request by niklasdewally**

### CODE REVIEW

**Comment by niklasdewally** [comment]
@ozgurakgun output so far: https://github.com/conjure-cp/conjure-oxide/actions/runs/12159352656/attempts/1#summary-33909301709

**Comment by ozgurakgun** [comment]
The output looks great. In the comment that gets posted, an overall aggregate per crate might be all we need, as long as the table is availabel as a job summary.

Something like:

```
Documentation coverage summary:
- crate name (7% documented, 2% has examples -- E/D/A)
- ...
- ...
```

where E is the number of examples, D is the number of documented, A is all.

Adding up what we see in the table essentially.

Not sure what you had in mind?

**Comment by niklasdewally** [comment]
> The output looks great. In the comment that gets posted, an overall aggregate per crate might be all we need, as long as the table is availabel as a job summary.
> 
> Something like:
> 
> ```
> Documentation coverage summary:
> - crate name (7% documented, 2% has examples -- E/D/A)
> - ...
> - ...
> ```
> 
> where E is the number of examples, D is the number of documented, A is all.
> 
> Adding up what we see in the table essentially.
> 
> Not sure what you had in mind?

In the comment, I was going to add a summary and a link to the full report for main and the PR.

Also maybe a summary per crate in the job summary itself.

**Comment by niklasdewally** [comment]
Final output:

https://github.com/conjure-cp/conjure-oxide/actions/runs/12164256382?pr=539

**Comment by niklasdewally** [comment]
@ozgurakgun if this all looks ok, could we merge this so I can test the PR comments?

**Comment by ozgurakgun** [comment]
go for it!

**Pull request merged**
