### PR TITLE
Build minion --quick

### PR DESCRIPTION
**Pull request by niklasdewally**

### CODE REVIEW

**Comment by ozgurakgun** [comment]
So do we always want to build minion with --quick? Did you want to do this because the last build took long?

The previous set of builds falied to find the cache and that's why they took long I think. Not sure why...

**Comment by niklasdewally** [comment]
> So do we always want to build minion with --quick? Did you want to do this because the last build took long?
> 
> The previous set of builds falied to find the cache and that's why they took long I think. Not sure why...

I made Felix clean build, and realised how slow it builds by default.

I have always gone into vendor and build by hand with debug or quick, so didn't notice!

**Comment by ozgurakgun** [comment]
ok, I'll merge for now but we should probably look into passing a command line argument through cargo to control the level of optimisation.

**Comment by niklasdewally** [comment]
> ok, I'll merge for now but we should probably look into passing a command line argument through cargo to control the level of optimisation.

In particular, I want to work out how to allow varying levels of  parallelisation of make (-jX). CI cannot parallelise so when I tried this before, it broke.

**Pull request merged**
