### PR TITLE
Finally fix CI for code coverage

### PR DESCRIPTION
**Pull request by niklasdewally**
See #47  #48

### CODE REVIEW

**Comment by niklasdewally** [comment]
@ozgurakgun good news! This PR has a coverage report!

the pain is over :)

**Comment by niklasdewally** [comment]
https://conjure-cp.github.io/conjure-oxide/coverage/7a3333ed7c41a8df25ff4c19b92cd23ed9b6273b/

**Comment by ozgurakgun** [comment]
Cool. The main directory gives a 404. Maybe we can manually rename latest to main now that it's renamed? 

https://conjure-cp.github.io/conjure-oxide/coverage/main/

Also (I am writing this in the wrong place, but) having an directory listing generated for the whole site would be good so we can get to the tools/ stuff etc by clicking about.

**Comment by niklasdewally** [comment]
> Cool. The main directory gives a 404. Maybe we can manually rename latest to main now that it's renamed?
> 
> https://conjure-cp.github.io/conjure-oxide/coverage/main/
> 
> Also (I am writing this in the wrong place, but) having an directory listing generated for the whole site would be good so we can get to the tools/ stuff etc by clicking about.

It's just because we haven't made any main commits yet.

**Comment by niklasdewally** [comment]
> Also (I am writing this in the wrong place, but) having an directory listing generated for the whole site would be good so we can get to the tools/ stuff etc by clicking about.

I've put this in #52

**Comment by ozgurakgun** [comment]
> Deleting or renaming latest is also a good idea.

OK, I'll do this.

**Comment by ozgurakgun** [comment]
the main directory isn't empty but lacks an index.html. is this also expected?

**Comment by niklasdewally** [comment]
> the main directory isn't empty but lacks an index.html. is this also expected?

It shouldnt have been filled - I have fixed this. (it was looking for branch name main, but this includes main branches of forks).

Also fixed the index

**Comment by niklasdewally** [comment]
Both of the above changes won't apply until merged, but they worked on my branch.

**Pull request merged**
