### PR TITLE
Added docstring to integration_test_inner

### PR DESCRIPTION
**Pull request by YehorBoiar**
Added docstring

### CODE REVIEW

**Comment by ozgurakgun** [comment]
a quick review @lixitrixi @gskorokhod @niklasdewally ?

**Review by lixitrixi — COMMENTED** [review]
Great documentation!

**Review by niklasdewally — APPROVED** [review]
Lgtm!

It would also be helpful to document the various environment variables used, but thats outside the scope of this change.

Thank you for this 🙏

**Comment by ozgurakgun** [comment]
> It would also be helpful to document the various environment variables used, but thats outside the scope of this change.

That's a good idea. Maybe @YehorBoiar can capture in an issue for later or better yet do it in a PR :)

Merging this now. Thanks for the quick reviews!

**Pull request merged**
